### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes

### ISSUE THREAD

**Issue by wilmardo** [nexe/resolve-dependencies#10]
```console
- Starting...
ℹ nexe 4.0.0-beta.15
✔ nexe 4.0.0-beta.15
- Finished in 1.976s
✔ Finished in 1.976s
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/zigbee2mqtt/node_modules/es5-ext/string/\x00#/contains/index.js'
    at Object.openSync (fs.js:468:10)
    at readFileSync (fs.js:377:35)
    at Object.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/node-loader.js:111:25)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:45:29)
    at /usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:78:14)
    at /usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:78:14)
```

When I look in the `/zigbee2mqtt/node_modules/es5-ext/string/` directory, there is a directory named `#` which seems to get encoded somewhere and it breaks.
```console
# ls -l /zigbee2mqtt/node_modules/es5-ext/string/
total 32
drwxr-xr-x    9 root     root          4096 Jan  2 18:23 #
-rw-r--r--    1 root     root           708 Oct 26  1985 format-method.js
drwxr-xr-x    2 root     root          4096 Jan  2 18:23 from-code-point
-rw-r--r--    1 root     root           287 Oct 26  1985 index.js
-rw-r--r--    1 root     root           291 Oct 26  1985 is-string.js
-rw-r--r--    1 root     root           205 Oct 26  1985 random-uniq.js
-rw-r--r--    1 root     root          1064 Oct 26  1985 random.js
drwxr-xr-x    2 root     root          4096 Jan  2 18:23 raw
```

The issue happened with the latest Nexe beta but the issue seems to be in this package. If it isn't the correct place to raise this issue, let me know :)

**Comment by wilmardo** [comment]
Oh and if you are short on time, let me know and I will try to debug some further!

**Comment by calebboyd** [comment]
looks like an issue that was resolved in enhanced-resolve already. Should be fixed in https://github.com/nexe/resolve-dependencies/commit/9ab5cf68d4e815688928636f64f215537c0f0a60

Thanks for the report!

**Comment by wilmardo** [comment]
Ai bad news, sadly is doesn't seem fixed by the latest dependency bump. I just retried with the newest beta16 but the same error:
```console
# nexe --build --target alpine --output zigbee2mqtt 
 ---> Running in c90444410a79
- Starting...
ℹ nexe 4.0.0-beta.16
✔ nexe 4.0.0-beta.16
- Finished in 1.988s
✔ Finished in 1.988s
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/zigbee2mqtt/node_modules/es5-ext/string/\x00#/contains/index.js'
    at Object.openSync (fs.js:468:10)
    at readFileSync (fs.js:377:35)
    at Object.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/node-loader.js:111:25)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:45:29)
    at /usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:78:14)
    at /usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:79:48
    at Array.map (<anonymous>)
    at Loader.load (/usr/lib/node_modules/nexe/node_modules/resolve-dependencies/lib/loader.js:78:14)
```

**Comment by calebboyd** [comment]
can you share what `npm ls enhanced-resolve` shows in your project with nexe installed?

**Comment by wilmardo** [comment]
Of the project:
```console
# npm ls enhanced-resolve
zigbee2mqtt@1.17.0 /zigbee2mqtt
`-- (empty)
```
Global installed nexe:
```
 # npm -g ls enhanced-resolve
/usr/lib
`-- nexe@4.0.0-beta.16
  `-- resolve-dependencies@6.0.4
    `-- enhanced-resolve@5.4.1
```

What is expected as output? It seems to be the version you specified in 

I created a branch with an easy to reproduce example:
https://github.com/LANsible/docker-zigbee2mqtt/tree/resolve-dependencies-bug

You can test it like this:
```
git clone https://github.com/LANsible/docker-zigbee2mqtt.git
cd docker-zigbee2mqtt
git checkout resolve-dependencies-bug
docker build . -t test
docker run -it test
```
That drops you to a rootshell within the project I am trying to build.

The source of the from image can be found here:
https://github.com/LANsible/docker-nexe

**Comment by wilmardo** [comment]
I am still seeing this issue with the beta17. Is there anything I can help to troubleshoot this?

**Comment by OmgImAlexis** [comment]
I believe this is the same issue.

https://github.com/nexe/resolve-dependencies/blob/4cb15f6307fd067af722a71068753328febc5f41/src/node-loader.ts#L116

Until this is properly fixed I'm using this patch.
```js
try {
    file.contents = readFileSync(absPath, 'utf-8');
} catch (error) {
    console.log('failed with %s', error.message);
    file.contents = readFileSync(absPath.replace('\x00', ''));
}
```

```
root@Devon:/usr/local/bin/node/api# ./node_modules/.bin/nexe ./dist/index.js 
ℹ nexe 4.0.0-beta.17
✔ nexe 4.0.0-beta.17
✔ Finished in 7.548s
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received '/usr/local/bin/node/api/node_modules/es5-ext/string/\x00#/contains/index.js'
```

**Comment by calebboyd** [comment]
If you can reinstall this should be fixed in a patch version
